notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
slack:
    secure: CTAiFdNpx+MubeXEU8Ru3/mnScnXZND7oC+nxeBzbAOoQis8qsgzPXYvNQhNzHpqgPLj1XHGk98z/6OAGmNhyrDtXg4zczISGcSUvW8CqkSBedsDkE8Ui3KbW3rS3sC2F+EdNjkpJyPOkf8Fn0tAukJxN8ax0A7JTH370kjOrWhQqJ1m1ydDW8cgXAyueC8SnSwrCKVjgoWAPuG9DcJWuc1SlnVOJf0Dg78m/pKgunhlH9pncKNYSxkJ0g9A1jlMyY5aLJyML542yfSL6oNiHsqUwYLFuqjHKc9YKrSuKA0FsRf6dE1gPawQnRGSpXWe4uYFWMEwZWGJ/F7+v8U2TJG8XVKb6DcRXJJDOal8k/fkVvRQhSqFnvYx4crNusUgjGkUehixFN4lhGhAAYbZOJeuwobfddP5JJp/Pv19+C3RjTJl/oKViQgPD/CodQMJmwP9Arh7Jbh0/bhtLDkQE4BefZeg1qtTOEEhcSOuCXK8aZZ7qPrea4Xd9+EgN094MEJrm+x8CN2oDvf8+moA4kdNpJUyioIC1Hcw7YXFNGmmPeGiNo7zmm3oWBSlz1ALWGkGkzyVVq+A8hvegfyEC4FJvcR1CN9LqXLWXmLdY6ZOrluVOvQL3HDhvJpOx5gI5X9kMQ5QpQ1QGHtDXoTdNQN3MmSsceNZZU03ngHtJss=
    rooms:
      secure: k9n2w73BK4l86sZ7GFZzo9dO1D1P6c3bNrmz3nZ5I2IRKeeqMdwe57m6rc7dQL2E99WAwaKTotxBvsXWECnFMSZ0hlWxPIYdZ2Aft62aWplpNHFV/8IBxVzsPuwGlj/q7g+UwAr0pZkzQ25yZd17weQLCsaOMFy/LnJ097z8APoQMM280DIGSi7OBaZGQyPoTV9nYDKLZEcvwmy6bcFjW5XceyaM1dDZAZJ4HccFs+J202aXf4B9LsPV0qHHsd240ghJ2vFGLlKsQ9fYyjmKYvKkVIqGRnq4dUMt62LdZayGzDlCe7Zn8FizoIkQFkEWPLpBFPGUXsY8LItHJKFy+O3CUNVqtu+VOkuB78iRkKC/MZiru5WXBFz6n9b17VVBQWx+MGyhmIEPbgDgDeLTGB1NtdkRkqYCRq0JniUZmobXNcKywU6K2OBJaB9aydAI8pMNs3QyIFf7BMVAg9Un8l4xRltSYkOJu6lTkwUn8BHJiSdKAsgSs3ktzCSWeTNZ79dEh9OzqXo5xDsDNPgXdO1ZvYo3+KjeCjLW8zRletl2W8w9AItmU/d7z9RBxv11IbhPubefiUyUVB3cZ6zRp0QFXNBKf4zJM6eoZd8nk5U/P6QzTPIWzA7MOR/o/wCZ2s1J1KNxTSqwkHBZLFZxgAphTW/tPJ21SxeaOpcMlO8=
      on_success: change # default: always
      on_failure: always # default: always
env:
  global:
    - MAKEFLAGS="-j 5"
language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gfortran-5

before_install:
  - export CC=gcc-5 && export CXX=g++-5 && export FC=gfortran-5
  - sudo apt-get -qq update
  - sudo apt-get install gsl-bin libgsl0-dev lib64ncurses5-dev
  - git clone https://github.com/unittest-cpp/unittest-cpp.git
  - cd unittest-cpp/builds/
  - cmake ../
  - sudo make -j4 install
  - cd ../../
  
before_script:
  - mkdir paass-build
  - cd paass-build
  - cmake ../ -DPAASS_BUILD_SCAN_UTILITIES=ON -DPAASS_BUILD_ACQ=OFF -DPAASS_BUILD_TESTS=ON -DPAASS_BUILD_UTKSCAN=ON -DPAASS_USE_ROOT=OFF

script:
  - make -j4

after_script:
  - cd ../
  - rm -rf paass-build
  - ls ~/
