notifications:
  email:
    on_success: change
    on_failure: always
slack:
    rooms:
      - secure: "k9n2w73BK4l86sZ7GFZzo9dO1D1P6c3bNrmz3nZ5I2IRKeeqMdwe57m6rc7dQL2E99WAwaKTotxBvsXWECnFMSZ0hlWxPIYdZ2Aft62aWplpNHFV/8IBxVzsPuwGlj/q7g+UwAr0pZkzQ25yZd17weQLCsaOMFy/LnJ097z8APoQMM280DIGSi7OBaZGQyPoTV9nYDKLZEcvwmy6bcFjW5XceyaM1dDZAZJ4HccFs+J202aXf4B9LsPV0qHHsd240ghJ2vFGLlKsQ9fYyjmKYvKkVIqGRnq4dUMt62LdZayGzDlCe7Zn8FizoIkQFkEWPLpBFPGUXsY8LItHJKFy+O3CUNVqtu+VOkuB78iRkKC/MZiru5WXBFz6n9b17VVBQWx+MGyhmIEPbgDgDeLTGB1NtdkRkqYCRq0JniUZmobXNcKywU6K2OBJaB9aydAI8pMNs3QyIFf7BMVAg9Un8l4xRltSYkOJu6lTkwUn8BHJiSdKAsgSs3ktzCSWeTNZ79dEh9OzqXo5xDsDNPgXdO1ZvYo3+KjeCjLW8zRletl2W8w9AItmU/d7z9RBxv11IbhPubefiUyUVB3cZ6zRp0QFXNBKf4zJM6eoZd8nk5U/P6QzTPIWzA7MOR/o/wCZ2s1J1KNxTSqwkHBZLFZxgAphTW/tPJ21SxeaOpcMlO8="
      on_success: change # default: always
      on_failure: always # default: always
env:
  global:
    - MAKEFLAGS="-j 5"
language: cpp
sudo: required
dist: trusty
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gfortran-5

before_install:
  - export CC=gcc-5 && export CXX=g++-5
  - sudo apt-get -qq update
  - sudo apt-get install gsl-bin libgsl0-dev lib64ncurses5-dev
  - git clone https://github.com/unittest-cpp/unittest-cpp.git
  - cd unittest-cpp/builds/
  - cmake ../
  - sudo make -j4 install
  - cd ../../
  
before_script:
  - mkdir paass-build
  - cd paass-build
  - cmake ../ -DPAASS_BUILD_SCAN_UTILITIES=ON -DPAASS_BUILD_ACQ=OFF -DPAASS_BUILD_TESTS=ON -DPAASS_BUILD_UTKSCAN=ON -DPAASS_USE_ROOT=OFF

script:
  - make -j4

after_script:
  - cd ../
  - rm -rf paass-build
  - ls ~/
